apiVersion: v2
name: kavita
description: Kavita reading server
type: application
version: 0.1.0
appVersion: v0.9.0.2
home: https://www.kavitareader.com/
sources:
  - https://github.com/Kareadita/Kavita
  - https://wiki.kavitareader.com/
maintainers:
  - name: Ammar Lakis
    url: https://github.com/ammarlakis
