{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kavita.serviceAccountName" . }}
  labels:
    {{- include "kavita.labels" . | nindent 4 }}
  {{- $annotations := include "kavita.annotations" . }}
  {{- if or $annotations .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $annotations }}
    {{- . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
